In [14]:
import pandas as pd
import glob
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:masterkey@localhost:5432/Projeto_BI')

print("Conectado")

Conectado

In [ ]:
# a biblioteca sys serve para acessar o interpretador Python e instalar as bibliotecas necessárias para a execução do código, como o SQLAlchemy e o psycopg2-binary, que são usados para conectar ao banco de dados PostgreSQL.
import sys
!{sys.executable} -m pip install sqlalchemy psycopg2-binary

In [13]:
caminho = './data/*.csv'
arquivo = glob.glob(caminho)
display(arquivo)
Fatura_df = pd.concat((pd.read_csv(i, sep = ';') for i in arquivo),ignore_index=True)
display(Fatura_df)

['./data\\Fatura_2025-03-20.csv',
 './data\\Fatura_2025-04-20.csv',
 './data\\Fatura_2025-05-20.csv',
 './data\\Fatura_2025-06-20.csv',
 './data\\Fatura_2025-07-20.csv',
 './data\\Fatura_2025-08-20.csv',
 './data\\Fatura_2025-09-20.csv',
 './data\\Fatura_2025-10-20.csv',
 './data\\Fatura_2025-11-20.csv',
 './data\\Fatura_2025-12-20.csv',
 './data\\Fatura_2026-01-20.csv',
 './data\\Fatura_2026-02-20.csv']

,Data de Compra,Nome no Cartão,Final do Cartão,Categoria,Descrição,Parcela,Valor (em US$),Cotação (em R$),Valor (em R$)
0,12/10/2024,VIN DIESEL,1115,Departamento / Desconto,HUB*NETSHOES,5/10,0.00,0.00,52.99
1,28/10/2024,VIN DIESEL,1115,Assistência médica e odontológica,OPTICA RUDI,5/10,0.00,0.00,162.00
2,16/11/2024,VIN DIESEL,1115,Supermercados / Mercearia / Padarias / Lojas d...,COTRIJAL,4/10,0.00,0.00,48.49
3,26/11/2024,VIN DIESEL,1115,Relacionados a Automotivo,RECUPERADORADEPAR,4/4,0.00,0.00,498.08
4,24/01/2025,VIN DIESEL,1115,Relacionados a Automotivo,EPIC MOTORS MECANICA,2/3,0.00,0.00,633.33
...,...,...,...,...,...,...,...,...,...
1940,01/02/2026,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,0.00,0.00,116.53
1941,01/02/2026,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,608.92,5.47,3329.39
1942,01/02/2026,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,0.00,0.00,116.53
1943,01/02/2026,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,608.92,5.47,-3329.39
1944,01/02/2026,EVA MENDES,1117,Serviços financeiros,BUNQ,Única,608.92,5.47,3329.39

In [ ]:
#ajuste de tabela / visualizadores para conferencia

#Fatura_df.columns
#Fatura_df.info()
#Fatura_df.head(3)
#Fatura_df['data_de_compra'].head(3)
Fatura_df.columns = (
    Fatura_df.columns
    .str.lower()
    .str.replace(' ', '_')
    .str.replace('ã', 'a')
    .str.replace('ç', 'c')
    .str.replace('(', '')
    .str.replace(')', '')
    .str.replace('$', 'S')
)

In [ ]:
#transformação dos dados

Fatura_df.columns = Fatura_df.columns.str.strip().str.lower() #padronizar os nomes das colunas
Fatura_df = Fatura_df.dropna()# remove valores nulos
Fatura_df = Fatura_df.drop_duplicates()# remove duplicadas
Fatura_df = Fatura_df[Fatura_df['valor_em_rs'] > 0] # remove valores negativos ou zero
Fatura_df = Fatura_df[Fatura_df['categoria'] != '-'] # remove linhas negativas ou sem categoria

Fatura_df['valor_em_rs'] = pd.to_numeric(
    Fatura_df['valor_em_rs']
    .astype(str)
    .str.replace('.', '', regex=False)   # remove milhar
    .str.replace(',', '.', regex=False), # corrige decimal
    errors='coerce'
)

Fatura_df['data_de_compra'] = pd.to_datetime(# transforma esse campo em data
    Fatura_df['data_de_compra'],
    dayfirst=True,
    errors='coerce'
)

display(Fatura_df)

In [ ]:
#quebrando as datas em partes para facilitar a análise

Fatura_df['ano'] = Fatura_df['data_de_compra'].dt.year #.dt é a propriedade de data e hora e .year é o atributo que extrai o ano da data
Fatura_df['mes'] = Fatura_df['data_de_compra'].dt.month #.month é o atributo que extrai o mês da data de compra
Fatura_df['mes_nome'] = Fatura_df['data_de_compra'].dt.month_name() #.month_name extrai o nome do mês
Fatura_df['dia_semana'] = Fatura_df['data_de_compra'].dt.day_name(locale='pt_BR') #.day_name é o método que extrai o nome do dia da semana

Fatura_df[['data_de_compra', 'ano', 'mes', 'dia_semana']].head()# exibe as colunas criadas

  data_de_compra   ano  mes     dia_semana
0     2024-10-12  2024   10         Sábado
1     2024-10-28  2024   10  Segunda-feira
2     2024-11-16  2024   11         Sábado
3     2024-11-26  2024   11    Terça-feira
4     2025-01-24  2025    1    Sexta-feira

In [ ]:
# célula feita para responder as perguntas de negócio
Fatura_df['valor_em_rs'].mean()# Valor médio gasto por transação

Fatura_df.groupby('dia_semana')['valor_em_rs'].sum().sort_values(ascending=False)# Total gasto por dia da semana

Fatura_df.groupby(['ano', 'mes'])['valor_em_rs'].sum()# Total gasto por mês e ano

Fatura_df.groupby('categoria')['valor_em_rs'].sum().sort_values(ascending=False)# Total gasto por categoria

Fatura_df.groupby('categoria')['valor_em_rs'].sum().idxmax()# Categoria com maior gasto


total = Fatura_df['valor_em_rs'].sum()

(Fatura_df.groupby('categoria')['valor_em_rs'].sum() / total) * 100# Percentual gasto por categoria em relação ao total

Fatura_df.to_sql('fato_transacao', engine, if_exists='replace', index=False)# Exporta o DataFrame para a tabela 'fato_transacao' no banco de dados, substituindo a tabela se ela já existir e sem incluir o índice do DataFrame como coluna na tabela.

111