In [8]:
import pandas as pd

In [9]:
#Fatura_df = pd.read_csv('data/Fatura_2025-03-20.csv')
Fatura_df = pd.read_csv('data/Fatura_2025-03-20.csv', sep=';')
display(Fatura_df)

,Data de Compra,Nome no Cartão,Final do Cartão,Categoria,Descrição,Parcela,Valor (em US$),Cotação (em R$),Valor (em R$)
0,12/10/2024,VIN DIESEL,1115,Departamento / Desconto,HUB*NETSHOES,5/10,0.0,0.0,52.99
1,28/10/2024,VIN DIESEL,1115,Assistência médica e odontológica,OPTICA RUDI,5/10,0.0,0.0,162.00
2,16/11/2024,VIN DIESEL,1115,Supermercados / Mercearia / Padarias / Lojas d...,COTRIJAL,4/10,0.0,0.0,48.49
3,26/11/2024,VIN DIESEL,1115,Relacionados a Automotivo,RECUPERADORADEPAR,4/4,0.0,0.0,498.08
4,24/01/2025,VIN DIESEL,1115,Relacionados a Automotivo,EPIC MOTORS MECANICA,2/3,0.0,0.0,633.33
...,...,...,...,...,...,...,...,...,...
111,04/03/2025,EVA MENDES,1117,Restaurante / Lanchonete / Bar,GARE ESTACAO,Única,0.0,0.0,20.90
112,04/03/2025,EVA MENDES,1117,Restaurante / Lanchonete / Bar,GARE ESTACAO,Única,0.0,0.0,62.70
113,06/03/2025,EVA MENDES,1117,Associação,MIX CENTER,Única,0.0,0.0,40.22
114,07/03/2025,EVA MENDES,1117,TV por assinatura / Serviços de rádio,NETFLIX.COM,Única,0.0,0.0,20.90
115,07/03/2025,EVA MENDES,1117,Restaurante / Lanchonete / Bar,CAMILALODI,Única,0.0,0.0,97.00

In [ ]:
# ajustando as tabelas para facilitar a análise

Fatura_df.columns
Fatura_df.info()
#Fatura_df.head(3)


#Fatura_df.columns = (
#    Fatura_df.columns
#    .str.strip()
#    .str.lower()
#    .str.replace(' ', '_')
#)

#Fatura_df['data_de_compra'].head(3)

<class 'pandas.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Data de Compra   116 non-null    str
 1   Nome no Cartão   116 non-null    str
 2   Final do Cartão  116 non-null    int64
 3   Categoria        116 non-null    str
 4   Descrição        116 non-null    str
 5   Parcela          116 non-null    str
 6   Valor (em US$)   116 non-null    float64
 7   Cotação (em R$)  116 non-null    float64
 8   Valor (em R$)    116 non-null    float64
dtypes: float64(3), int64(1), str(5)
memory usage: 8.3 KB

In [ ]:
#transformação dos dados

Fatura_df.columns = Fatura_df.columns.str.strip().str.lower() #padronizar os nomes das colunas

Fatura_df = Fatura_df.dropna()# remove linhas com valores nulos

Fatura_df = Fatura_df.drop_duplicates()# remove linhas duplicadas

Fatura_df = Fatura_df[Fatura_df['valor_(em_r$)'] > 0] # remove linhas com valores negativos ou zero

Fatura_df = Fatura_df[Fatura_df['categoria'] != '-'] # remove linhas com categoria '-'


Fatura_df['valor_(em_r$)'] = pd.to_numeric(
    Fatura_df['valor_(em_r$)']
    .astype(str)
    .str.replace('.', '', regex=False)   # remove milhar
    .str.replace(',', '.', regex=False), # corrige decimal
    errors='coerce'
)

Fatura_df['data_de_compra'] = pd.to_datetime(
    Fatura_df['data_de_compra'],
    dayfirst=True,
    errors='coerce'
)

display(Fatura_df)

,data_de_compra,nome_no_cartão,final_do_cartão,categoria,descrição,parcela,valor_(em_us$),cotação_(em_r$),valor_(em_r$)
0,2024-10-12,VIN DIESEL,1115,Departamento / Desconto,HUB*NETSHOES,5/10,0.0,0.0,5299
1,2024-10-28,VIN DIESEL,1115,Assistência médica e odontológica,OPTICA RUDI,5/10,0.0,0.0,1620
2,2024-11-16,VIN DIESEL,1115,Supermercados / Mercearia / Padarias / Lojas d...,COTRIJAL,4/10,0.0,0.0,4849
3,2024-11-26,VIN DIESEL,1115,Relacionados a Automotivo,RECUPERADORADEPAR,4/4,0.0,0.0,49808
4,2025-01-24,VIN DIESEL,1115,Relacionados a Automotivo,EPIC MOTORS MECANICA,2/3,0.0,0.0,63333
...,...,...,...,...,...,...,...,...,...
110,2025-03-04,EVA MENDES,1117,Restaurante / Lanchonete / Bar,GARE ESTACAO,Única,0.0,0.0,209
112,2025-03-04,EVA MENDES,1117,Restaurante / Lanchonete / Bar,GARE ESTACAO,Única,0.0,0.0,627
113,2025-03-06,EVA MENDES,1117,Associação,MIX CENTER,Única,0.0,0.0,4022
114,2025-03-07,EVA MENDES,1117,TV por assinatura / Serviços de rádio,NETFLIX.COM,Única,0.0,0.0,209
115,2025-03-07,EVA MENDES,1117,Restaurante / Lanchonete / Bar,CAMILALODI,Única,0.0,0.0,970

In [12]:
#quebrando as datas em partes para facilitar a análise

Fatura_df['ano'] = Fatura_df['data_de_compra'].dt.year #.dt é a propriedade de acesso a atributos de data e hora e .year é o atributo que extrai o ano da data de compra
Fatura_df['mes'] = Fatura_df['data_de_compra'].dt.month #.month é o atributo que extrai o mês da data de compra
Fatura_df['mes_nome'] = Fatura_df['data_de_compra'].dt.month_name() #.month_name() é o método que extrai o nome do mês da data de compra
Fatura_df['dia_semana'] = Fatura_df['data_de_compra'].dt.day_name(locale='pt_BR') #.day_name() é o método que extrai o nome do dia da semana da data de compra

Fatura_df[['data_de_compra', 'ano', 'mes', 'dia_semana']].head()

  data_de_compra   ano  mes     dia_semana
0     2024-10-12  2024   10         Sábado
1     2024-10-28  2024   10  Segunda-feira
2     2024-11-16  2024   11         Sábado
3     2024-11-26  2024   11    Terça-feira
4     2025-01-24  2025    1    Sexta-feira

In [13]:
Fatura_df['valor_(em_r$)'].mean()# Valor médio das compras

Fatura_df.groupby('dia_semana')['valor_(em_r$)'].sum().sort_values(ascending=False)# Total gasto por dia da semana

Fatura_df.groupby(['ano', 'mes'])['valor_(em_r$)'].sum()# Total gasto por mês e ano

Fatura_df.groupby('categoria')['valor_(em_r$)'].sum().sort_values(ascending=False)# Total gasto por categoria

Fatura_df.groupby('categoria')['valor_(em_r$)'].sum().sort_values(ascending=False)# Total gasto por categoria, ordenado do maior para o menor

Fatura_df.groupby('categoria')['valor_(em_r$)'].sum().idxmax()# Categoria com maior gasto


total = Fatura_df['valor_(em_r$)'].sum()

(Fatura_df.groupby('categoria')['valor_(em_r$)'].sum() / total) * 100# Percentual gasto por categoria em relação ao total

categoria
Assistência médica e odontológica                                1.505852
Associação                                                      15.711439
Casa / Escritório Mobiliário                                     1.122372
Departamento / Desconto                                          6.051474
Educacional                                                      3.417489
Elétrico                                                         3.419557
Empresa para empresa                                             0.268702
Entretenimento                                                   0.886169
Especialidade varejo                                             0.210648
Materiais de construção para casa                                0.127630
Relacionados a Automotivo                                       24.045474
Restaurante / Lanchonete / Bar                                   5.090412
Seguro                                                           3.833024
Serviços Profissionais                                           0.032351
Serviços pessoais                                                0.826343
Supermercados / Mercearia / Padarias / Lojas de Conveniência     9.773265
T&E Companhia aérea                                             20.371692
TV por assinatura / Serviços de rádio                            0.030873
Transporte                                                       3.127959
Vestuário / Roupas                                               0.147276
Name: valor_(em_r$), dtype: float64