In [ ]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine('postgresql://postgres:masterkey@localhost:5432/Projeto_BI')

print("Conectado")

Conectado com sucesso

In [ ]:

import sys
!{sys.executable} -m pip install sqlalchemy psycopg2-binary

In [ ]:
#Fatura_df = pd.read_csv('data/Fatura_2025-03-20.csv')
Fatura_df = pd.read_csv('data/Fatura_2025-03-20.csv', sep=';')
display(Fatura_df)

In [17]:
# ajustando as tabelas para facilitar a análise

#Fatura_df.columns
Fatura_df.info()
#Fatura_df.head(3)
Fatura_df.columns = (
    Fatura_df.columns
    .str.lower()
    .str.replace(' ', '_')
    .str.replace('ã', 'a')
    .str.replace('ç', 'c')
    .str.replace('(', '')
    .str.replace(')', '')
    .str.replace('$', 'S')
)


#Fatura_df.columns = (
#    Fatura_df.columns
#    .str.strip()
#    .str.lower()
#    .str.replace(' ', '_')
#)

#Fatura_df['data_de_compra'].head(3)

<class 'pandas.DataFrame'>
Index: 111 entries, 0 to 115
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   data_de_compra   111 non-null    datetime64[us]
 1   nome_no_cartao   111 non-null    str
 2   final_do_cartao  111 non-null    int64
 3   categoria        111 non-null    str
 4   descricao        111 non-null    str
 5   parcela          111 non-null    str
 6   valor_em_uss     111 non-null    float64
 7   cotacao_em_rs    111 non-null    float64
 8   valor_em_rs      111 non-null    int64
 9   ano              111 non-null    int32
 10  mes              111 non-null    int32
 11  mes_nome         111 non-null    str
 12  dia_semana       111 non-null    str
dtypes: datetime64[us](1), float64(2), int32(2), int64(2), str(6)
memory usage: 11.3 KB

In [18]:
#transformação dos dados

Fatura_df.columns = Fatura_df.columns.str.strip().str.lower() #padronizar os nomes das colunas

Fatura_df = Fatura_df.dropna()# remove linhas com valores nulos

Fatura_df = Fatura_df.drop_duplicates()# remove linhas duplicadas

Fatura_df = Fatura_df[Fatura_df['valor_em_rs'] > 0] # remove linhas com valores negativos ou zero

Fatura_df = Fatura_df[Fatura_df['categoria'] != '-'] # remove linhas com categoria '-'






Fatura_df['valor_em_rs'] = pd.to_numeric(
    Fatura_df['valor_em_rs']
    .astype(str)
    .str.replace('.', '', regex=False)   # remove milhar
    .str.replace(',', '.', regex=False), # corrige decimal
    errors='coerce'
)

Fatura_df['data_de_compra'] = pd.to_datetime(
    Fatura_df['data_de_compra'],
    dayfirst=True,
    errors='coerce'
)

display(Fatura_df)

,data_de_compra,nome_no_cartao,final_do_cartao,categoria,descricao,parcela,valor_em_uss,cotacao_em_rs,valor_em_rs,ano,mes,mes_nome,dia_semana
0,2024-10-12,VIN DIESEL,1115,Departamento / Desconto,HUB*NETSHOES,5/10,0.0,0.0,5299,2024,10,October,Sábado
1,2024-10-28,VIN DIESEL,1115,Assistência médica e odontológica,OPTICA RUDI,5/10,0.0,0.0,1620,2024,10,October,Segunda-feira
2,2024-11-16,VIN DIESEL,1115,Supermercados / Mercearia / Padarias / Lojas d...,COTRIJAL,4/10,0.0,0.0,4849,2024,11,November,Sábado
3,2024-11-26,VIN DIESEL,1115,Relacionados a Automotivo,RECUPERADORADEPAR,4/4,0.0,0.0,49808,2024,11,November,Terça-feira
4,2025-01-24,VIN DIESEL,1115,Relacionados a Automotivo,EPIC MOTORS MECANICA,2/3,0.0,0.0,63333,2025,1,January,Sexta-feira
...,...,...,...,...,...,...,...,...,...,...,...,...,...
110,2025-03-04,EVA MENDES,1117,Restaurante / Lanchonete / Bar,GARE ESTACAO,Única,0.0,0.0,209,2025,3,March,Terça-feira
112,2025-03-04,EVA MENDES,1117,Restaurante / Lanchonete / Bar,GARE ESTACAO,Única,0.0,0.0,627,2025,3,March,Terça-feira
113,2025-03-06,EVA MENDES,1117,Associação,MIX CENTER,Única,0.0,0.0,4022,2025,3,March,Quinta-feira
114,2025-03-07,EVA MENDES,1117,TV por assinatura / Serviços de rádio,NETFLIX.COM,Única,0.0,0.0,209,2025,3,March,Sexta-feira
115,2025-03-07,EVA MENDES,1117,Restaurante / Lanchonete / Bar,CAMILALODI,Única,0.0,0.0,970,2025,3,March,Sexta-feira

In [19]:
#quebrando as datas em partes para facilitar a análise

Fatura_df['ano'] = Fatura_df['data_de_compra'].dt.year #.dt é a propriedade de acesso a atributos de data e hora e .year é o atributo que extrai o ano da data de compra
Fatura_df['mes'] = Fatura_df['data_de_compra'].dt.month #.month é o atributo que extrai o mês da data de compra
Fatura_df['mes_nome'] = Fatura_df['data_de_compra'].dt.month_name() #.month_name() é o método que extrai o nome do mês da data de compra
Fatura_df['dia_semana'] = Fatura_df['data_de_compra'].dt.day_name(locale='pt_BR') #.day_name() é o método que extrai o nome do dia da semana da data de compra

Fatura_df[['data_de_compra', 'ano', 'mes', 'dia_semana']].head()

  data_de_compra   ano  mes     dia_semana
0     2024-10-12  2024   10         Sábado
1     2024-10-28  2024   10  Segunda-feira
2     2024-11-16  2024   11         Sábado
3     2024-11-26  2024   11    Terça-feira
4     2025-01-24  2025    1    Sexta-feira

In [22]:
Fatura_df['valor_em_rs'].mean()# Valor médio das compras

Fatura_df.groupby('dia_semana')['valor_em_rs'].sum().sort_values(ascending=False)# Total gasto por dia da semana

Fatura_df.groupby(['ano', 'mes'])['valor_em_rs'].sum()# Total gasto por mês e ano

Fatura_df.groupby('categoria')['valor_em_rs'].sum().sort_values(ascending=False)# Total gasto por categoria

Fatura_df.groupby('categoria')['valor_em_rs'].sum().idxmax()# Categoria com maior gasto


total = Fatura_df['valor_em_rs'].sum()

(Fatura_df.groupby('categoria')['valor_em_rs'].sum() / total) * 100# Percentual gasto por categoria em relação ao total

Fatura_df.to_sql('fato_transacao', engine, if_exists='replace', index=False)# Exporta o DataFrame para a tabela 'fato_transacao' no banco de dados, substituindo a tabela se ela já existir e sem incluir o índice do DataFrame como coluna na tabela.

111