In [1]:
import pandas as pd

In [4]:
Fatura_df = pd.read_csv('data/Fatura_2025-03-20.csv')
display(Fatura_df)

    Data de Compra;Nome no Cartão;Final do Cartão;Categoria;Descrição;Parcela;Valor (em US$);Cotação (em R$);Valor (em R$)
0    12/10/2024;VIN DIESEL;1115;Departamento / Desc...
1    28/10/2024;VIN DIESEL;1115;Assistência médica ...
2    16/11/2024;VIN DIESEL;1115;Supermercados / Mer...
3    26/11/2024;VIN DIESEL;1115;Relacionados a Auto...
4    24/01/2025;VIN DIESEL;1115;Relacionados a Auto...
..                                                 ...
111  04/03/2025;EVA MENDES;1117;Restaurante / Lanch...
112  04/03/2025;EVA MENDES;1117;Restaurante / Lanch...
113  06/03/2025;EVA MENDES;1117;Associação;MIX CENT...
114  07/03/2025;EVA MENDES;1117;TV por assinatura /...
115  07/03/2025;EVA MENDES;1117;Restaurante / Lanch...

[116 rows x 1 columns]

In [16]:
Fatura_df.columns
#Fatura_df.info()
#Fatura_df.head(3)
#Fatura_df = pd.read_csv('data/Fatura_2025-03-20.csv', sep=';')

Index(['Data de Compra', 'Nome no Cartão', 'Final do Cartão', 'Categoria',
       'Descrição', 'Parcela', 'Valor (em US$)', 'Cotação (em R$)',
       'Valor (em R$)'],
      dtype='str')

In [19]:
Fatura_df.columns = Fatura_df.columns.str.strip().str.lower() #padronizar os nomes das colunas

Fatura_df = Fatura_df.dropna()# remove linhas com valores nulos

Fatura_df = Fatura_df.drop_duplicates()# remove linhas duplicadas

Fatura_df['valor (em r$)'] = pd.to_numeric(
    Fatura_df['valor (em r$)'].astype(str).str.replace(',', '.'),
    errors='coerce'
)

Fatura_df['data de compra'] = pd.to_datetime(
    Fatura_df['data de compra'],
    errors='coerce'
)

display(Fatura_df)

,data de compra,nome no cartão,final do cartão,categoria,descrição,parcela,valor (em us$),cotação (em r$),valor (em r$)
0,2024-12-10,VIN DIESEL,1115,Departamento / Desconto,HUB*NETSHOES,5/10,0.0,0.0,52.99
1,NaT,VIN DIESEL,1115,Assistência médica e odontológica,OPTICA RUDI,5/10,0.0,0.0,162.00
2,NaT,VIN DIESEL,1115,Supermercados / Mercearia / Padarias / Lojas d...,COTRIJAL,4/10,0.0,0.0,48.49
3,NaT,VIN DIESEL,1115,Relacionados a Automotivo,RECUPERADORADEPAR,4/4,0.0,0.0,498.08
4,NaT,VIN DIESEL,1115,Relacionados a Automotivo,EPIC MOTORS MECANICA,2/3,0.0,0.0,633.33
...,...,...,...,...,...,...,...,...,...
110,2025-04-03,EVA MENDES,1117,Restaurante / Lanchonete / Bar,GARE ESTACAO,Única,0.0,0.0,20.90
112,2025-04-03,EVA MENDES,1117,Restaurante / Lanchonete / Bar,GARE ESTACAO,Única,0.0,0.0,62.70
113,2025-06-03,EVA MENDES,1117,Associação,MIX CENTER,Única,0.0,0.0,40.22
114,2025-07-03,EVA MENDES,1117,TV por assinatura / Serviços de rádio,NETFLIX.COM,Única,0.0,0.0,20.90
115,2025-07-03,EVA MENDES,1117,Restaurante / Lanchonete / Bar,CAMILALODI,Única,0.0,0.0,97.00